### PR TITLE
allow Angular 1.5.x

### PR DESCRIPTION
**Pull request by antonlegkiy**

### CODE REVIEW

**Comment by jtrussell** [comment]
Thanks! I'm sorry, I should have specified - we'll need to update the `bower.json` in this repo as well so the tests get run on our CI server with the new version of angular.

https://github.com/jtrussell/angular-snap.js/blob/master/bower.json#L10-L13

**Comment by antonlegkiy** [comment]
I'm sorry, my fault.

**Comment by antonlegkiy** [comment]
Justin, perhaps I make something wrong?

**Comment by jtrussell** [comment]
Nope - perfect. I just hadn't had a chance to merge yet :). Will publish shortly.

**Comment by antonlegkiy** [comment]
Thx a lot, Justin! :)

**Pull request merged**
